export { default as Info } from "./personalInfo/PersonalInfoLayout"
export { default as Plans } from "./selectPlan/SelectPlanLayout"
export { default as PickAddOns } from "./addOns/AddOnsLayout"
export { default as FinshedPage } from "./finishingUp/FinishingLayout"
export { default as ThankYou } from "./thankYou/ThankyouLayout"
